<a href="https://colab.research.google.com/github/anshuiitb/pytorch/blob/main/torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch

In [15]:

import numpy as np
np = np.random.rand(3,4)
np

array([[0.84725718, 0.54863216, 0.48971373, 0.74984747],
       [0.80670861, 0.66652548, 0.12112158, 0.13562161],
       [0.76464135, 0.92102732, 0.00662843, 0.0583192 ]])

In [5]:
np.dtype

dtype('float64')

In [19]:
tensor = torch.rand(3,4)
tensor

tensor([[0.6829, 0.9829, 0.6268, 0.3526],
        [0.6710, 0.8218, 0.3285, 0.8557],
        [0.0914, 0.9276, 0.5818, 0.5456]])

In [16]:
tensor = torch.tensor(np)

In [17]:
tensor

tensor([[0.8473, 0.5486, 0.4897, 0.7498],
        [0.8067, 0.6665, 0.1211, 0.1356],
        [0.7646, 0.9210, 0.0066, 0.0583]], dtype=torch.float64)

In [20]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
#reshape also if we don't know the item range , using -1
my_torch2= torch.arange(15)
my_torch2 = my_torch2.reshape(-1 ,3)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [27]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
my_torch4 = my_torch3.view(-1,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [32]:
#with reshape and view , they will update

In [33]:
#slices , grab a section of your tensor
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
my_torch5[7]

tensor(7)

In [37]:
my_torch6 = my_torch5.reshape(5,2)
my_torch6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [38]:
my_torch6[:,1]

tensor([1, 3, 5, 7, 9])

In [39]:
my_torch6[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [40]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [41]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [45]:
tensor_a / tensor_b # ** power


tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
tensor_a.add_(tensor_b) # permanent changes in tensor_a

simple NN